VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "docker" do |d|
    d.pull_images "registry"
    d.run "registry",
      args: "-p 5000:5000"
  end
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "dockerregistry.yml"
  end
end